### ISSUE TITLE
Import and Name Errors in nfinder.py File

### ISSUE THREAD

**Issue by shibarjun** [r-hyperspec/pyspc-unmix#1]
There's an underscore in the class name "OneToOneFeatureMixin" in the nfinder.py file causing import and name errors. I believe it should be removed.

Thank you.

from sklearn.base import BaseEstimator, TransformerMixin, **_OneToOneFeatureMixin**
ImportError: cannot import name '_OneToOneFeatureMixin' from 'sklearn.base'

class NFINDR(**_OneToOneFeatureMixin**, TransformerMixin, BaseEstimator):
                 ^^^^^^^^^^^^^^^^^^^^^
NameError: name '_OneToOneFeatureMixin' is not defined.

**Comment by rguliev** [comment]
Thank you for pointing out.
Apparently, it had to do with package versions. Please, check the latest version.
